[backends]
  [backends.backend-plexwebtools]
    [backends.backend-plexwebtools.servers]
      [backends.backend-plexwebtools.servers.server-plexwebtools-ext]
        url = "http://192.168.5.90:33400/"
        weight = 0
[frontends]
  [frontends.frontend-plexwebtools]
    backend = "backend-plexwebtools"
    passHostHeader = true
    [frontends.frontend-plexwebtools.routes]
          [frontends.frontend-plexwebtools.routes.route-plexwebtools-ext]
        rule = "Host:pwt.example.com"
    [frontends.frontend-plexwebtools.headers]
      SSLRedirect = true
      SSLHost = "pwt.example.com"
      SSLForceHost = true
      STSSeconds = 315360000
      STSIncludeSubdomains = true
      STSPreload = true
      forceSTSHeader = true
      frameDeny = true
      contentTypeNosniff = true
      browserXSSFilter = true
      customFrameOptionsValue="allow-from https:example.com"
    [frontends.frontend-plexwebtools.auth]
      headerField = "X-WebAuth-User"
      [frontends.frontend-plexwebtools.auth.forward]
        address = "http://oauth:4181"
        trustForwardHeader = true
        authResponseHeaders = ["X-Forwarded-User"]